'use strict';

const nodemailer = require('nodemailer');

const transporter = nodemailer.createTransport({
  host:   process.env.MAIL_HOST || 'smtp.gmail.com',
  port:   parseInt(process.env.MAIL_PORT || '587'),
  secure: false,
  auth: {
    user: process.env.MAIL_USER,
    pass: process.env.MAIL_PASS,
  },
});

/**
 * Send tenant invitation email.
 * @param {string} toEmail  - Recipient
 * @param {string} company  - Company name
 * @param {string} token    - Signed invitation JWT
 */
async function sendInviteEmail(toEmail, company, token) {
  const link = `${process.env.BASE_URL}/onboarding?invite=${token}`;

  await transporter.sendMail({
    from:    process.env.MAIL_FROM || '"Logistics OS" <noreply@logisticsos.io>',
    to:      toEmail,
    subject: `You've been invited to Logistics OS`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;">
        <h2 style="color:#0f2235;margin-bottom:8px;">Welcome to Logistics OS</h2>
        <p style="color:#475569;line-height:1.6;">
          You've been invited to create an admin workspace for <strong>${company}</strong>.
          Click the button below to choose your subscription and complete your account setup.
        </p>
        <p style="color:#64748b;font-size:13px;margin-top:4px;">
          This link expires in <strong>48 hours</strong>.
        </p>
        <a href="${link}"
           style="display:inline-block;margin-top:24px;padding:12px 28px;background:#0f2235;
                  color:#fff;text-decoration:none;border-radius:8px;font-weight:700;font-size:14px;">
          Set Up My Workspace
        </a>
        <p style="margin-top:28px;font-size:12px;color:#94a3b8;">
          If you didn't expect this email, you can safely ignore it.<br/>
          Your workspace is private and isolated from all other companies on this platform.
        </p>
      </div>
    `,
  });
}

async function sendRegistrationEmail(email, fullName, companyName, slug, downloadLink) {
  // downloadLink is the PERMANENT token link generated by user.js
  // e.g. https://logistihub.ddns.net/amogus/get-app?token=<jwt_no_expiry>
 
  const subject = `Welcome to ${companyName} — Download Your App`;
 
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
 
          <!-- Header -->
          <tr>
            <td style="background:#0a1628;padding:32px;text-align:center;">
              <div style="font-size:28px;margin-bottom:8px;">📦</div>
              <div style="color:#ffffff;font-size:20px;font-weight:800;letter-spacing:-0.02em;">${companyName}</div>
              <div style="color:#94a3b8;font-size:12px;margin-top:4px;">Powered by Logistics OS</div>
            </td>
          </tr>
 
          <!-- Body -->
          <tr>
            <td style="padding:32px;">
              <h1 style="font-size:22px;font-weight:800;color:#0a1628;margin:0 0 8px;">Welcome, ${fullName}! 🎉</h1>
              <p style="color:#64748b;font-size:14px;line-height:1.6;margin:0 0 24px;">
                Your account has been successfully created for <strong>${companyName}</strong>.
                Use the link below to download the mobile app and start tracking your shipments.
              </p>
 
              <!-- Download Button -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;">
                <tr>
                  <td align="center">
                    <a href="${downloadLink}"
                       style="display:inline-block;background:#0a1628;color:#ffffff;font-size:15px;font-weight:700;padding:14px 32px;border-radius:12px;text-decoration:none;">
                      📱 Download the App
                    </a>
                  </td>
                </tr>
              </table>
 
              <!-- Raw link (fallback) -->
              <p style="font-size:12px;color:#94a3b8;text-align:center;word-break:break-all;margin:0 0 24px;">
                Or copy this link:<br>
                <a href="${downloadLink}" style="color:#0a1628;">${downloadLink}</a>
              </p>
 
              <!-- Steps -->
              <div style="background:#f8fafc;border-radius:12px;padding:16px 18px;margin-bottom:24px;">
                <div style="font-size:12px;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:12px;">How to install</div>
                <div style="font-size:13px;color:#475569;line-height:1.6;">
                  <div style="margin-bottom:8px;">① Tap the download button above</div>
                  <div style="margin-bottom:8px;">② Install the APK on your Android device</div>
                  <div>③ Log in with your registered email</div>
                </div>
              </div>
 
              <p style="font-size:12px;color:#94a3b8;margin:0;">
                This link is permanent — you can use it anytime to re-download the app.
              </p>
            </td>
          </tr>
 
          <!-- Footer -->
          <tr>
            <td style="background:#f8fafc;padding:16px 32px;text-align:center;">
              <p style="font-size:11px;color:#cbd5e1;margin:0;">
                © ${new Date().getFullYear()} ${companyName} · Powered by Logistics OS
              </p>
            </td>
          </tr>
 
        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;
 
  // Use whatever transporter you already have (nodemailer, etc.)
  await transporter.sendMail({
    from:    process.env.MAIL_FROM || `"${companyName}" <noreply@logistihub.ddns.net>`,
    to:      email,
    subject,
    html,
  });
}

module.exports = { sendRegistrationEmail };
/**
 * Send welcome email after admin account is created.
 */
async function sendWelcomeEmail(toEmail, adminName, companyName, slug) {
  const adminUrl    = `${process.env.BASE_URL}/${slug}/admin`;
  const registerUrl = `${process.env.BASE_URL}/${slug}/register`;

  await transporter.sendMail({
    from:    process.env.MAIL_FROM,
    to:      toEmail,
    subject: `Your Logistics OS workspace is live — ${companyName}`,
    html: `
      <div style="font-family:sans-serif;max-width:520px;margin:0 auto;padding:32px 24px;">
        <h2 style="color:#0f2235;">Your workspace is ready, ${adminName}!</h2>
        <p style="color:#475569;line-height:1.6;">
          <strong>${companyName}</strong>'s private Logistics OS workspace has been activated.
        </p>
        <div style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin:20px 0;">
          <p style="margin:0 0 8px;font-size:13px;font-weight:700;color:#0f2235;">Your private URLs</p>
          <p style="margin:4px 0;font-size:12px;color:#64748b;">
            Admin dashboard: <a href="${adminUrl}" style="color:#3b82f6;">${adminUrl}</a>
          </p>
          <p style="margin:4px 0;font-size:12px;color:#64748b;">
            Staff registration: <a href="${registerUrl}" style="color:#3b82f6;">${registerUrl}</a>
          </p>
        </div>
        <p style="font-size:12px;color:#94a3b8;">
          Keep your registration URL private — only share it with your own staff and drivers.
        </p>
      </div>
    `,
  });
}

module.exports = { sendInviteEmail, sendWelcomeEmail, sendRegistrationEmail };
