// ─── PASTE THIS INTO config/mailer.js ────────────────────────────────────────
// Replace your existing sendRegistrationEmail function with this one.
// The only change: it now accepts a 5th argument `downloadLink` and
// includes both a clickable button and the raw URL in the email body.

async function sendRegistrationEmail(email, fullName, companyName, slug, downloadLink) {
  // downloadLink is the PERMANENT token link generated by user.js
  // e.g. https://logistihub.ddns.net/amogus/get-app?token=<jwt_no_expiry>

  const subject = `Welcome to ${companyName} — Download Your App`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 20px;">
    <tr>
      <td align="center">
        <table width="100%" cellpadding="0" cellspacing="0" style="max-width:480px;background:#ffffff;border-radius:20px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">

          <!-- Header -->
          <tr>
            <td style="background:#0a1628;padding:32px;text-align:center;">
              <div style="font-size:28px;margin-bottom:8px;">📦</div>
              <div style="color:#ffffff;font-size:20px;font-weight:800;letter-spacing:-0.02em;">${companyName}</div>
              <div style="color:#94a3b8;font-size:12px;margin-top:4px;">Powered by Logistics OS</div>
            </td>
          </tr>

          <!-- Body -->
          <tr>
            <td style="padding:32px;">
              <h1 style="font-size:22px;font-weight:800;color:#0a1628;margin:0 0 8px;">Welcome, ${fullName}! 🎉</h1>
              <p style="color:#64748b;font-size:14px;line-height:1.6;margin:0 0 24px;">
                Your account has been successfully created for <strong>${companyName}</strong>.
                Use the link below to download the mobile app and start tracking your shipments.
              </p>

              <!-- Download Button -->
              <table width="100%" cellpadding="0" cellspacing="0" style="margin-bottom:16px;">
                <tr>
                  <td align="center">
                    <a href="${downloadLink}"
                       style="display:inline-block;background:#0a1628;color:#ffffff;font-size:15px;font-weight:700;padding:14px 32px;border-radius:12px;text-decoration:none;">
                      📱 Download the App
                    </a>
                  </td>
                </tr>
              </table>

              <!-- Raw link (fallback) -->
              <p style="font-size:12px;color:#94a3b8;text-align:center;word-break:break-all;margin:0 0 24px;">
                Or copy this link:<br>
                <a href="${downloadLink}" style="color:#0a1628;">${downloadLink}</a>
              </p>

              <!-- Steps -->
              <div style="background:#f8fafc;border-radius:12px;padding:16px 18px;margin-bottom:24px;">
                <div style="font-size:12px;font-weight:700;color:#475569;text-transform:uppercase;letter-spacing:0.07em;margin-bottom:12px;">How to install</div>
                <div style="font-size:13px;color:#475569;line-height:1.6;">
                  <div style="margin-bottom:8px;">① Tap the download button above</div>
                  <div style="margin-bottom:8px;">② Install the APK on your Android device</div>
                  <div>③ Log in with your registered email</div>
                </div>
              </div>

              <p style="font-size:12px;color:#94a3b8;margin:0;">
                This link is permanent — you can use it anytime to re-download the app.
              </p>
            </td>
          </tr>

          <!-- Footer -->
          <tr>
            <td style="background:#f8fafc;padding:16px 32px;text-align:center;">
              <p style="font-size:11px;color:#cbd5e1;margin:0;">
                © ${new Date().getFullYear()} ${companyName} · Powered by Logistics OS
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>`;

  // Use whatever transporter you already have (nodemailer, etc.)
  await transporter.sendMail({
    from:    process.env.MAIL_FROM || `"${companyName}" <noreply@logistihub.ddns.net>`,
    to:      email,
    subject,
    html,
  });
}

module.exports = { sendRegistrationEmail };
// ─────────────────────────────────────────────────────────────────────────────